### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jostyee** [500degrees/zero-chi#1]
Hi, I wonder how to use this repo as a chi middleware, any guidance?

**Comment by ocalvet** [comment]
Hi @jostyee we built this middleware for a project we were using it to try to generalize the use of zerolog. How do you plan to use it?

**Comment by jostyee** [comment]
@ocalvet I'd like to send constructed logs json to syslog while keep using [zerolog.ConsoleWriter](https://github.com/rs/zerolog#pretty-logging) to make console more readable.
